--Creación de base de datos 
USE MASTER
GO

IF EXISTS(Select * FROM SysDataBases WHERE name='TiendaCrediYi')
BEGIN
	DROP DATABASE TiendaCrediYi
END
go

CREATE DATABASE TiendaCrediYi
go

USE TiendaCrediYi
GO

----------------------------------------------------------------------------------------------------------
--Tablas

CREATE TABLE CLIENTE
(
	IDCLIENTE INT IDENTITY NOT NULL ,
	TIPODOCUMENTO VARCHAR(20) NOT NULL,
	CHECK ((TIPODOCUMENTO = 'PASAPORTE') OR (TIPODOCUMENTO = 'CI')),
	DOCUMENTO INT UNIQUE NOT NULL,  
	NOMBRE VARCHAR(30) NOT NULL,
	EMAIL VARCHAR(20) CHECK (EMAIL LIKE '%_@__%.__%') NOT NULL,
	TELEFONO INT NOT NULL,
	PRIMARY KEY(IDCLIENTE)
)
GO


CREATE TABLE EMPLEADO
(
	DOCUMENTO INT NOT NULL UNIQUE,  
	NOMBRE VARCHAR(30) NOT NULL,
	CONTRASENA VARCHAR (15) NOT NULL,
	PRIMARY KEY(DOCUMENTO)
)
GO

CREATE TABLE PRODUCTO
(
	IDPRODUCTO INT NOT NULL UNIQUE,
	DESCRIPCION VARCHAR(50) NOT NULL,
	IMPORTE MONEY,  
	PRIMARY KEY(IDPRODUCTO)
)
GO

CREATE TABLE COMPRACABEZAL
(
	IDCABEZAL INT IDENTITY NOT NULL,
	SERIE VARCHAR(1) NOT NULL,
	NUMERO INT NOT NULL,
	IDCLIENTE INT NOT NULL FOREIGN KEY REFERENCES CLIENTE(IDCLIENTE),
	FECHA DATETIME DEFAULT GETDATE() NOT NULL,
	TOTALCOMPRA MONEY,
	PRIMARY KEY(IDCABEZAL)
)
GO

CREATE TABLE LINEACABEZAL
(
	IDLINEA INT IDENTITY NOT NULL ,
	IDCABEZAL INT NOT NULL FOREIGN KEY REFERENCES COMPRACABEZAL(IDCABEZAL),
	IDPRODUCTO INT NOT NULL FOREIGN KEY REFERENCES PRODUCTO(IDPRODUCTO),
	CANTIDAD INT NOT NULL,
	PRIMARY KEY(IDLINEA, IDCABEZAL)
)
GO
------------------------------------------------------------------------------------------------------------------------------
--Stores Procedures


CREATE PROCEDURE ALTACOMPRACABEZAL
@SERIE VARCHAR(1),
@NUMERO INT,
@IDCLIENTE INT,
@FECHA DATETIME, 
@TOTAL MONEY
AS
BEGIN
	INSERT COMPRACABEZAL VALUES(@SERIE, @NUMERO, @IDCLIENTE, @FECHA, @TOTAL)	
	IF @@ERROR <> 0
	BEGIN
		RETURN -1
	END
	RETURN scope_IDENTITY()
END

GO


CREATE PROCEDURE ALTACOMPRALINEA
@IDCABEZAL INT, 
@IDPROD INT, 
@CANTIDAD INT
AS
BEGIN
	IF NOT EXISTS(SELECT * FROM PRODUCTO WHERE IDPRODUCTO = @IDPROD)
		RETURN -1
	IF NOT EXISTS (SELECT * FROM COMPRACABEZAL WHERE IDCABEZAL = @IDCABEZAL)
		RETURN -2
		
	INSERT LINEACABEZAL VALUES(@IDCABEZAL, @IDPROD, @CANTIDAD)
	
	IF @@ERROR <> 0
	BEGIN
		RETURN -3
	END

END
GO 


CREATE PROC BUSCARCABEZAL
@IDCABEZAL INT
AS
BEGIN
	SELECT * FROM COMPRACABEZAL
	WHERE IDCABEZAL = @IDCABEZAL
END 
GO


CREATE PROCEDURE LISTADOCOMPRASCLIENTE
@DOCUMENTOCLI INT 
AS 
BEGIN 
	IF NOT EXISTS(SELECT * FROM CLIENTE WHERE DOCUMENTO = @DOCUMENTOCLI)
	 RETURN -1
	SELECT  IDCABEZAL, SERIE, NUMERO, COMPRACABEZAL.IDCLIENTE, FECHA, TOTALCOMPRA
	FROM COMPRACABEZAL RIGHT JOIN CLIENTE 
	on COMPRACABEZAL.IDCLIENTE = CLIENTE.IDCLIENTE 
	WHERE @DOCUMENTOCLI = CLIENTE.DOCUMENTO
END 
GO


CREATE PROCEDURE LISTADOCOMPRAS
AS 
BEGIN 
	SELECT * FROM COMPRACABEZAL
END 
GO 

CREATE PROCEDURE LISTADOLINEAS 
@IDCABEZAL INT
AS 
BEGIN 
	SELECT * FROM LINEACABEZAL
	WHERE IDCABEZAL = @IDCABEZAL
END 

GO

-------------------------------------------------------------------------------------------------------------

CREATE PROC BUSCARPRODUCTO 
@IDPRODUCTO INT
AS
BEGIN
	SELECT * FROM PRODUCTO
	WHERE IDPRODUCTO = @IDPRODUCTO
END 
GO

CREATE PROCEDURE LISTARPRODUCTO
AS 
BEGIN 
	SELECT * FROM PRODUCTO
END 
GO

---------------------------------------------------------------------------------------------------------------

CREATE PROC BUSCARCLIENTE 
@IDCLIENTE INT
AS
BEGIN
	SELECT * FROM CLIENTE
	WHERE IDCLIENTE = @IDCLIENTE
END 
GO

CREATE PROC BUSCARCLIENTEXDOC
@DOCUMENTO INT
AS
BEGIN
	SELECT * FROM CLIENTE
	WHERE DOCUMENTO = @DOCUMENTO
END 
GO


---------------------------------------------------------------------------------------------------------------
CREATE PROCEDURE LOGUEO
@DOCUMENTO INT,
@CONTRASENA VARCHAR(15)
AS
BEGIN
	if(exists(SELECT * from EMPLEADO where @DOCUMENTO = Documento))
		SELECT * FROM EMPLEADO 
		WHERE DOCUMENTO = @DOCUMENTO AND CONTRASENA = @CONTRASENA
END
GO
------------------------------------------------------------------------------------------------------------
--Datos de prueba 


INSERT INTO CLIENTE(TIPODOCUMENTO, DOCUMENTO, NOMBRE, EMAIL, TELEFONO) VALUES ('CI', 21112221, 'Maria Pérez', 'maria@mail.com', 098175566)
INSERT INTO CLIENTE(TIPODOCUMENTO, DOCUMENTO, NOMBRE, EMAIL, TELEFONO) VALUES ('CI', 12223331, 'Pedro Gómez', 'pedro@gmail.com', 095896355)
INSERT INTO CLIENTE(TIPODOCUMENTO, DOCUMENTO, NOMBRE, EMAIL, TELEFONO) VALUES ('PASAPORTE', 502632, 'Ana López', 'analopez@gmail.com', 099562312)
GO 

INSERT INTO EMPLEADO(DOCUMENTO, NOMBRE, CONTRASENA) VALUES (33333333, 'Alicia Rodiguez', 'abc1234')
GO 

INSERT INTO PRODUCTO(IDPRODUCTO, DESCRIPCION, IMPORTE) VALUES (1,'Licuadora', 1500)
INSERT INTO PRODUCTO(IDPRODUCTO, DESCRIPCION, IMPORTE) VALUES (2,'Cafetera', 2000)
INSERT INTO PRODUCTO(IDPRODUCTO, DESCRIPCION, IMPORTE) VALUES (3,'Batidora', 750)
INSERT INTO PRODUCTO(IDPRODUCTO, DESCRIPCION, IMPORTE) VALUES (4,'Microondas', 1890)
INSERT INTO PRODUCTO(IDPRODUCTO, DESCRIPCION, IMPORTE) VALUES (5, 'Heladera', 16900)
GO
